steps:
  - id: 'Run unit test and e2e test'
    name: 'ubuntu'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        apt-get update
        apt-get install -y curl gnupg unzip xvfb libxi6 libgconf-2-4 wget
        curl -sL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs
        npm install -g npm@9
        node -v
        npm -v
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        apt install -y ./google-chrome-stable_current_amd64.deb
        export CHROME_BIN='/usr/bin/google-chrome'
        npm i -g @angular/cli
        npm install
        ng test --watch=false --browsers=ChromeHeadlessNoSandbox
        nohup ng serve &
        npx cypress run --headless

  - id: 'Build Docker image'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/sport-app-angular:$SHORT_SHA',
      '.'
      ]

  - id: 'Push the Docker image to Google Container Registry'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/sport-app-angular:$SHORT_SHA'
      ]

  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'sport-app-angular',
      '--image',
      'gcr.io/$PROJECT_ID/sport-app-angular:$SHORT_SHA',
      '--platform',
      'managed',
      '--region',
      'us-central1',
      '--allow-unauthenticated',
      '--port',
      '80',
      '--timeout',
      '900'
      ]
