steps:
  - name: "Instalar dependencias de Node"
    image: "node:lts-alpine"
    command: ["npm", "install"]

  - name: "Construir aplicación Angular"
    image: "node:lts-alpine"
    command: ["ng", "build", "--prod"]

  - name: "Copiar archivos a la imagen de Docker"
    image: "gcr.io/cloudbuilders/docker"
    command: ["docker", "cp", "-a", "dist", "/app"]

  - name: "Construir imagen de Docker"
    image: "gcr.io/cloudbuilders/docker"
    command: ["docker", "build", "-t", "gcr.io/proyecto2-grupo1/sport-app-angular", "."]

  - name: "Empujar imagen de Docker al Registro de Google Cloud"
    image: "gcr.io/cloudbuilders/docker"
    command: ["docker", "push", "gcr.io/proyecto2-grupo1/sport-app-angular"]

  - name: "Desplegar la aplicación en Google App Engine"
    image: "gcr.io/google-appengine/standard-python37"
    command: ["gcloud", "app", "deploy", "app.yaml", "--project", "proyecto2-grupo1"]
